### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by leonferguson** [mariofusco/drools-rete-builder#1]
When building the drools-rete-builder project again 6.4.0-SNAPSHOT master, drools-datasource, and drools-model  I receive the below error:

Is there some other branch I need to use

Thanks,

[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.drools:drools-rete-builder:jar:6.4.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 64, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building drools-rete-builder 6.4.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ drools-rete-builder ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\dev\IdeaProjects\drools-rete-builder\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ drools-rete-builder ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 18 source files to C:\dev\IdeaProjects\drools-rete-builder\target\classes
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/CanonicalReteBuilder.java: Some input files use unchecked or unsafe operations.
[WARNING] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/CanonicalReteBuilder.java: Recompile with -Xlint:unchecked for details.
[INFO] 2 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/nodes/PhreakAsyncInvokerNode.java:[4,30] cannot find symbol
  symbol:   class LeftTupleSets
  location: package org.drools.core.common
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/nodes/PhreakAsyncInvokerNode.java:[17,24] cannot find symbol
  symbol:   class LeftTupleSets
  location: class org.drools.retebuilder.nodes.PhreakAsyncInvokerNode
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/nodes/PhreakAsyncInvokerNode.java:[18,24] cannot find symbol
  symbol:   class LeftTupleSets
  location: class org.drools.retebuilder.nodes.PhreakAsyncInvokerNode
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/nodes/PhreakAsyncInvokerNode.java:[19,24] cannot find symbol
  symbol:   class LeftTupleSets
  location: class org.drools.retebuilder.nodes.PhreakAsyncInvokerNode
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/nodes/DataStreamNode.java:[124,26] cannot find symbol
  symbol:   method notifyHalt()
  location: variable workingMemory of type org.drools.core.common.InternalWorkingMemory
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/nodes/AsyncInvokerNode.java:[18,8] org.drools.retebuilder.nodes.AsyncInvokerNode is not abstract and does not override abstract method createLeftTuple(org.drools.core.reteoo.LeftTuple,org.drools.core.reteoo.RightTuple,org.drools.core.reteoo.LeftTuple,org.drools.core.reteoo.LeftTuple,org.drools.core.reteoo.Sink,boolean) in org.drools.core.reteoo.LeftTupleSink
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/nodes/AsyncInvokerNode.java:[66,5] method does not override or implement a method from a supertype
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/nodes/AsyncInvokerNode.java:[71,5] method does not override or implement a method from a supertype
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/nodes/AsyncInvokerNode.java:[76,5] method does not override or implement a method from a supertype
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/nodes/AsyncInvokerNode.java:[81,5] method does not override or implement a method from a supertype
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/nodes/AsyncInvokerNode.java:[86,5] method does not override or implement a method from a supertype
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/constraints/LambdaConstraint.java:[11,8] org.drools.retebuilder.constraints.LambdaConstraint is not abstract and does not override abstract method isAllowed(org.drools.core.common.InternalFactHandle,org.drools.core.common.InternalWorkingMemory) in org.drools.core.spi.AlphaNodeFieldConstraint
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/constraints/LambdaConstraint.java:[39,5] method does not override or implement a method from a supertype
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/constraints/LambdaConstraint.java:[41,73] cannot find symbol
  symbol:   method getLeftTuple()
  location: class org.drools.retebuilder.constraints.LambdaConstraint.LambdaContextEntry
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/constraints/LambdaConstraint.java:[46,73] cannot find symbol
  symbol:   method getLeftTuple()
  location: class org.drools.retebuilder.constraints.LambdaConstraint.LambdaContextEntry
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/constraints/LambdaConstraint.java:[49,5] method does not override or implement a method from a supertype
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/constraints/LambdaDataProvider.java:[18,8] org.drools.retebuilder.constraints.LambdaDataProvider is not abstract and does not override abstract method getResults(org.drools.core.spi.Tuple,org.drools.core.common.InternalWorkingMemory,org.drools.core.spi.PropagationContext,java.lang.Object) in org.drools.core.spi.DataProvider
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/constraints/LambdaDataProvider.java:[38,5] method does not override or implement a method from a supertype
[INFO] 18 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.818 s
[INFO] Finished at: 2015-12-07T09:19:32-08:00
[INFO] Final Memory: 18M/382M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project drools-rete-builder: Compilation failure: Compilation failure:
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/nodes/PhreakAsyncInvokerNode.java:[4,30] cannot find symbol
[ERROR] symbol:   class LeftTupleSets
[ERROR] location: package org.drools.core.common
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/nodes/PhreakAsyncInvokerNode.java:[17,24] cannot find symbol
[ERROR] symbol:   class LeftTupleSets
[ERROR] location: class org.drools.retebuilder.nodes.PhreakAsyncInvokerNode
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/nodes/PhreakAsyncInvokerNode.java:[18,24] cannot find symbol
[ERROR] symbol:   class LeftTupleSets
[ERROR] location: class org.drools.retebuilder.nodes.PhreakAsyncInvokerNode
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/nodes/PhreakAsyncInvokerNode.java:[19,24] cannot find symbol
[ERROR] symbol:   class LeftTupleSets
[ERROR] location: class org.drools.retebuilder.nodes.PhreakAsyncInvokerNode
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/nodes/DataStreamNode.java:[124,26] cannot find symbol
[ERROR] symbol:   method notifyHalt()
[ERROR] location: variable workingMemory of type org.drools.core.common.InternalWorkingMemory
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/nodes/AsyncInvokerNode.java:[18,8] org.drools.retebuilder.nodes.AsyncInvokerNode is not abstract and does not override abstract method createLeftTuple(org.drools.core.reteoo.LeftTuple,org.drools.core.reteoo.RightTuple,org.drools.core.reteoo.LeftTuple,org.drools.core.reteoo.LeftTuple,org.drools.core.reteoo.Sink,boolean) in org.drools.core.reteoo.LeftTupleSink
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/nodes/AsyncInvokerNode.java:[66,5] method does not override or implement a method from a supertype
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/nodes/AsyncInvokerNode.java:[71,5] method does not override or implement a method from a supertype
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/nodes/AsyncInvokerNode.java:[76,5] method does not override or implement a method from a supertype
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/nodes/AsyncInvokerNode.java:[81,5] method does not override or implement a method from a supertype
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/nodes/AsyncInvokerNode.java:[86,5] method does not override or implement a method from a supertype
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/constraints/LambdaConstraint.java:[11,8] org.drools.retebuilder.constraints.LambdaConstraint is not abstract and does not override abstract method isAllowed(org.drools.core.common.InternalFactHandle,org.drools.core.common.InternalWorkingMemory) in org.drools.core.spi.AlphaNodeFieldConstraint
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/constraints/LambdaConstraint.java:[39,5] method does not override or implement a method from a supertype
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/constraints/LambdaConstraint.java:[41,73] cannot find symbol
[ERROR] symbol:   method getLeftTuple()
[ERROR] location: class org.drools.retebuilder.constraints.LambdaConstraint.LambdaContextEntry
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/constraints/LambdaConstraint.java:[46,73] cannot find symbol
[ERROR] symbol:   method getLeftTuple()
[ERROR] location: class org.drools.retebuilder.constraints.LambdaConstraint.LambdaContextEntry
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/constraints/LambdaConstraint.java:[49,5] method does not override or implement a method from a supertype
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/constraints/LambdaDataProvider.java:[18,8] org.drools.retebuilder.constraints.LambdaDataProvider is not abstract and does not override abstract method getResults(org.drools.core.spi.Tuple,org.drools.core.common.InternalWorkingMemory,org.drools.core.spi.PropagationContext,java.lang.Object) in org.drools.core.spi.DataProvider
[ERROR] /C:/dev/IdeaProjects/drools-rete-builder/src/main/java/org/drools/retebuilder/constraints/LambdaDataProvider.java:[38,5] method does not override or implement a method from a supertype
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by mariofusco** [comment]
Sorry, I made some change drools-core but didn't update my drools pojo
rules related projects accordingly.
I'll fix them asap.

Cheers,
Mario

**Comment by leonferguson** [comment]
This looks great.  

Looking forward to it.

Thanks,

Leon
